### ISSUE TITLE
Can't upload media

### ISSUE THREAD

**Issue by paulrobertlloyd** [benjifs/sparkles#13]
Sparkles can now interact with an Indiekit server’s Micropub media endpoint: it is recognised, and previous uploads are shown in the UI:

<img width="560" alt="Image upload interface" src="https://github.com/benjifs/sparkles/assets/813383/50a68216-6224-4b60-bebb-ba1f0b1c2f5b">

If I try to upload an image however, my Indiekit server returns a ‘No file included in request’ error. This is the incoming request:

```text
POST /media
headers {
  ﻿host: 'indiekit.up.railway.app',
﻿  accept: '*/*',
﻿  'accept-encoding': 'gzip, deflate, br',
﻿  authorization: 'Bearer XXXXXX',
  ﻿'content-length': '61601',
﻿  'content-type': 'multipart/form-data; boundary=----WebKitFormBoundaryMNzWqXaY74EidO2a',
﻿  'user-agent': 'node-fetch',
﻿  'x-forwarded-for': 'XX.XXX.XXX.XX',
﻿  'x-forwarded-proto': 'https',
﻿  'x-envoy-external-address': 'XX.XXX.XXX.XX',
﻿  'x-request-id': 'fc5332d9-cd00-414c-b21d-bd12c6465f60'
﻿}
```

This is the returned error:

```text
IndiekitError [BadRequestError]: No file included in request
  ﻿at IndiekitError.badRequest (file:///app/packages/error/index.js:5:12)
﻿  at actionController (file:///app/packages/endpoint-media/lib/controllers/action.js:33:31)
  ﻿at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
  ﻿at next (/app/node_modules/express/lib/router/route.js:144:13)
  ﻿at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
  ﻿at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
  ﻿at /app/node_modules/express/lib/router/index.js:284:15
﻿  at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12)
﻿  at next (/app/node_modules/express/lib/router/index.js:280:10)
﻿  at Function.handle (/app/node_modules/express/lib/router/index.js:175:3) {
﻿    code: 'bad_request',
﻿    status: 400
﻿  }
```

**Comment by benjifs** [comment]
I just pushed some changes which include a fix for this. I was sending the file as `photo` instead of `file`. Don't know why I did that when I did but should work now

**Comment by paulrobertlloyd** [comment]
Ah, that’d be it. Just tested, and it works! 🎉 Thanks so much for persisting with fixing these issues.

**Comment by paulrobertlloyd** [comment]
Have added Sparkles to [list of clients tested to work with Indiekit](https://getindiekit.com/clients).

**Comment by benjifs** [comment]
Awesome! Thanks for your help with testing and finding these issues.
